---
- name: 'Test playbook to sleep for a specified interval'
  hosts: all
  gather_facts: false
  vars:
    sleep_interval: 10

  tasks:
    - name: sleep for a specified interval
      command: sleep 50
   
    - name: 50 second pause
      pause:
        seconds: 50
